Repository muxable/rtchat, pull requests merged in 2023-02, with the labels that each got.

#900 feat: wired up shoutout
  functions/src/eventsub.ts
  lib/components/chat_history/message.dart
  lib/components/chat_history/twitch/shoutout_event.dart
  lib/models/adapters/messages.dart
  lib/models/messages/twitch/shoutout_create_event.dart
  lib/models/messages/twitch/shoutout_receive_event.dart
Labels: codeball:needs-careful-review

#928 fix: properly access fields from search/channels response
  functions/src/search.ts
Labels: codeball:approved

#930 chore: add shoutout scopes to twitch auth redirect
  functions/src/auth.ts
Labels: codeball:approved

#933 chore: replaced textlink shoutout with eventsub shoutout in inbound raid
  lib/components/chat_history/twitch/raid_event.dart
Labels: codeball:needs-careful-review

#934 chore: bump dependencies
  pubspec.yaml
Labels: codeball:approved

#936 feat: request chatter read permissions
  functions/src/auth.ts
Labels: codeball:approved

#935 chore: migrate to new chatters api
  functions/src/chat-status.ts
Labels: codeball:needs-careful-review

#940 fix: no document to update errors
  functions/src/subscriptions.ts
Labels: codeball:approved

#942 fix: handle 404 channel
  functions/src/index.ts
Labels: codeball:approved

#941 fix: coerce undefined email to null
  functions/src/auth.ts
Labels: codeball:needs-careful-review

#945 fix: remove unnecessary setState() call
  lib/components/message_input.dart
Labels: codeball:approved

#946 fix: missing image
  android/app/src/main/res/drawable/branding.png
Labels: codeball:approved

#947 chore: eventsub shoutout, from beta to version 1
  functions/src/eventsub.ts
Labels: codeball:needs-careful-review

#948 chore: update dependencies
  ios/Podfile.lock
Labels: dependencies, codeball:approved

#939 feat: branding for ios
  assets/branding.png
  ios/Runner/Assets.xcassets/BrandingImage.imageset/BrandingImage.png
  ios/Runner/Assets.xcassets/BrandingImage.imageset/BrandingImage@2x.png
  ios/Runner/Assets.xcassets/BrandingImage.imageset/BrandingImage@3x.png
  ios/Runner/Assets.xcassets/BrandingImage.imageset/Contents.json
  ios/Runner/Assets.xcassets/LaunchBackground.imageset/Contents.json
  ios/Runner/Assets.xcassets/LaunchBackground.imageset/background.png
  ios/Runner/Assets.xcassets/LaunchBackground.imageset/darkbackground.png
  ios/Runner/Base.lproj/LaunchScreen.storyboard
Labels: codeball:needs-careful-review

#957 chore: cleanup
  assets/LaunchImage.png
  assets/LaunchImage@2x.png
  assets/LaunchImage@3x.png
Labels: codeball:approved

#965 feat: add translations to timeout dialog
  lib/components/chat_history/timeout_dialog.dart
  lib/l10n/app_en.arb
Labels: codeball:approved

#966 fix: add missing l10n
  lib/components/drawer/sidebar.dart
  lib/l10n/app_en.arb
Labels: codeball:approved

#960 fix: remove exclamation mark
  lib/screens/settings/settings.dart
Labels: codeball:needs-careful-review
